#!/bin/sh

# Shortcut to execute commands.
docker compose exec php bash -c "cd /var/www && php artisan module:list"
#docker compose exec php bash -c "cd /var/www && php artisan module:dump"

read -p "Select a module: " module
echo "\n"

#  ⇂ module:v6:migrate
#  ⇂ module:make
#  ⇂ module:make-command
#  ⇂ module:make-component
#  ⇂ module:make-component-view
#  ⇂ module:make-controller
#  ⇂ module:make-event
#  ⇂ module:make-factory
#  ⇂ module:make-job
#  ⇂ module:make-listener
#  ⇂ module:make-mail
#  ⇂ module:make-middleware
#  ⇂ module:make-migration
#  ⇂ module:make-model
#  ⇂ module:make-notification
#  ⇂ module:make-policy
#  ⇂ module:make-provider
#  ⇂ module:make-request
#  ⇂ module:make-resource
#  ⇂ module:make-rule
#  ⇂ module:make-seed
#  ⇂ module:make-test
#  ⇂ module:migrate-fresh
#  ⇂ module:migrate-refresh
#  ⇂ module:migrate-reset
#  ⇂ module:migrate-rollback
#  ⇂ module:migrate-status
#  ⇂ module:publish-config
#  ⇂ module:publish-migration
#  ⇂ module:publish-translation
#  ⇂ module:route-provider

declare -a action=(
  [1]=install
  [2]=setup
  [3]=update
  [4]=enable
  [5]=disable
  [6]=migrate
  [7]=publish
  [8]=seed
  [9]=use
  [10]=unuse
  [11]=delete
)
for i in "${!action[@]}"; do
  echo "$i. module:${action[$i]}"
done

# shellcheck disable=SC2162
read -p "Select an action: " index

# shellcheck disable=SC2039
if [ -z ${action[$index]} ]; then
  echo "The option you chosen is invalid."
  exit
fi

case $index in
  11 )
    # shellcheck disable=SC2162
    read -p "Are you sure you want to delete this module (y/n) ? " deleteModuleAnswer
    if [ "$deleteModuleAnswer" != "${deleteModuleAnswer#[Yy]}" ] ; then
      sh ./scripts/app php artisan module:delete "${module}"
      sh ./scripts/app php artisan migrate:fresh --seed --force --env=local # Refresh all modules migrations.
      sh ./scripts/app php artisan module:seed # seed all modules
    fi
    exit
    ;;
  * )
    # shellcheck disable=SC2039
    sh ./scripts/app php artisan module:"${action[$index]}" "${module}"
    exit
    ;;
esac




